import os

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/twopiece/baseline/gray_128/rgb/      --seed 100   --dataset twopiece-gray   --batch-size 32   --epochs 100 --dimension 128   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/twopiece/baseline/gray_128/rgb/      --seed 100   --dataset twopiece-gray   --batch-size 32   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/twopiece/baseline/gray_128/rgb_l2/   --seed 100   --dataset twopiece-gray   --batch-size 32   --epochs 150 --dimension 128   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/twopiece/baseline/gray_128/rgb_l2/   --seed 100   --dataset twopiece-gray   --batch-size 32   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/rgb_l2/       --seed 100   --dataset onepiece-gray   --batch-size 32   --epochs 300 --dimension 256   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/rgb_l2/       --seed 100   --dataset onepiece-gray   --batch-size 32   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/lab_l2/       --seed 100   --dataset onepiece-gray   --batch-size 32   --epochs 300 --dimension 256   --lr 3e-4   --baseline True   --color-space lab')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/lab_l2/       --seed 100   --dataset onepiece-gray   --batch-size 32   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/lab_l2/       --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_l2/           --seed 100   --dataset onepiece-mono   --batch-size 32   --epochs 300 --dimension 256   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_l2/           --seed 100   --dataset onepiece-mono   --batch-size 32   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_l2/           --seed 100   --dataset onepiece-mono   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/lab_l2/         --seed 100   --dataset bleach-gray     --batch-size 32   --epochs 300 --dimension 256   --lr 3e-4   --baseline True   --color-space lab')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/lab_l2/         --seed 100   --dataset bleach-gray     --batch-size 32   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre_l2/           --seed 100   --dataset onepiece-thre   --batch-size 32   --epochs 300 --dimension 256   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre_l2/           --seed 100   --dataset onepiece-thre   --batch-size 32   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/thre_l2/             --seed 100   --dataset bleach-thre     --batch-size 32   --epochs 300 --dimension 256   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/thre_l2/             --seed 100   --dataset bleach-thre     --batch-size 32   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_128_l2/       --seed 100   --dataset onepiece-mono   --batch-size 32   --epochs 200 --dimension 128   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_128_l2/       --seed 100   --dataset onepiece-mono   --batch-size 32   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre_128_l2/       --seed 100   --dataset onepiece-thre   --batch-size 32   --epochs 200 --dimension 128   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre_128_l2/       --seed 100   --dataset onepiece-thre   --batch-size 32   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/rgb_l2/         --seed 100   --dataset bleach-gray     --batch-size 32   --epochs 300 --dimension 256   --lr 3e-4   --baseline True   --color-space rgb')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/rgb_l2/         --seed 100   --dataset bleach-gray     --batch-size 32   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python train.py       --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray_128/lab_l2/   --seed 100   --dataset onepiece-gray   --batch-size 32   --epochs 200 --dimension 128   --lr 3e-4   --baseline True   --color-space lab')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray_128/lab_l2/   --seed 100   --dataset onepiece-gray   --batch-size 32   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')



# os.system('python test-eval.py   --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/rgb/          --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/rgb_l2/       --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/lab/          --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono/              --seed 100   --dataset onepiece-mono   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre/              --seed 100   --dataset onepiece-thre   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray_128/rgb/      --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray_128/lab/      --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_128/          --seed 100   --dataset onepiece-mono   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre_128/          --seed 100   --dataset onepiece-thre   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/rgb/            --seed 100   --dataset bleach-gray     --batch-size 91   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/lab/            --seed 100   --dataset bleach-gray     --batch-size 91   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/thre/                --seed 100   --dataset bleach-thre     --batch-size 91   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/twopiece/baseline/gray_128/rgb/      --seed 100   --dataset twopiece-gray   --batch-size 138  --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')

# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray/lab_l2/       --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_l2/           --seed 100   --dataset onepiece-mono   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre_l2/           --seed 100   --dataset onepiece-thre   --batch-size 86   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray_l2/rgb/       --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/gray_128/lab_l2/   --seed 100   --dataset onepiece-gray   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/mono_128_l2/       --seed 100   --dataset onepiece-mono   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/onepiece/baseline/thre_128_l2/       --seed 100   --dataset onepiece-thre   --batch-size 86   --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/rgb_l2/         --seed 100   --dataset bleach-gray     --batch-size 91   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/gray/lab_l2/         --seed 100   --dataset bleach-gray     --batch-size 91   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space lab   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/bleach/baseline/thre_l2/             --seed 100   --dataset bleach-thre     --batch-size 91   --epochs 1   --dimension 256   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')
# os.system('python test-eval.py   --checkpoints-path /raid/hlcv-projects/student_directories/team06/checkpoints/twopiece/baseline/gray_128/rgb_l2/   --seed 100   --dataset twopiece-gray   --batch-size 138  --epochs 1   --dimension 128   --lr 3e-4   --baseline True   --color-space rgb   --evaluate-type False')